FlySearch.Web/Models/ErrorViewModel.cs
using System;

namespace FlySearch.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FlySearch.Web/Controllers/HomeController.cs
using FlySearch.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FlySearch.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FlySearch.Web/Controllers/VFlightTransportController.cs
using FlySearch.Core.DTOs;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace FlySearch.Web.Controllers
{
    public class VFlightTransportController : Controller
    {
        private readonly IHttpClientFactory _ClientFactory;

        public VFlightTransportController(IHttpClientFactory clientFactory)
        {
            _ClientFactory = clientFactory;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details()
        {

            List<VFlightTransportDTO> flightList = new List<VFlightTransportDTO>();
            using (var httpClient = new HttpClient())
            {
                using (var apiPetition = await httpClient.GetAsync("https://localhost:44305/api/VFlightTransport"))
                {
                    string apiResponse = await apiPetition.Content.ReadAsStringAsync();
                    flightList = JsonConvert.DeserializeObject<List<VFlightTransportDTO>>(apiResponse);
                }
            }
            return Json(flightList);

        }


    }
}

FlySearch.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Flights Page";
}

<div class="text-center">
    <h1 class="display-4">Flights example</h1>
    <p>This is an example to searching flights in this page, to see you have to click the botton "Flights" in the top bar.</p>
    
</div>

FlySearch.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlySearch.Web</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/Tabulator/dist/js/tabulator.js"></script>
    <link href="~/lib/Tabulator/dist/css/tabulator.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VFlightTransport" asp-action="Index">Flights</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FlySearch
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>

FlySearch.Web/Views/VFlightTransport/FlightTransport.cshtml
@{ ViewBag.Title = "Obtain flight transport";                Layout = "~/Views/Shared/_Layout.cshtml";}

FlySearch.Web/Views/VFlightTransport/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/js/Web/VFligtTransport.js"></script>

<h1>Flights</h1>


<div id="TabulatorFligth">

</div>


<script type="text/javascript">

    var rut = new function ()
    {
        this.urlFlightTransport = "@Url.Action("Details", "VFlightTransport")"
    }

</script>